version: '3'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: ronaldocutrim/people-app:prod
    volumes:
      - .:/app/
    container_name: node
    networks:
      - nodenet
  db:
    image: mysql
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=people
      - MYSQL_ROOT_PASSWORD=docker
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    networks:
      - nodenet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - app
    image: ronaldocutrim/nginx:prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodenet
networks:
  nodenet:
    driver: bridge
